class Info {
  String municipality;
  String imageUrl;
  String description;
  List barangay;
  List elementary;
  List highSchool;
  List college;

  Info({
    this.municipality,
    this.imageUrl,
    this.description,
    this.barangay,
    this.elementary,
    this.highSchool,
    this.college,
  });
}

List elementary1 = [
  'Alubijid Central School',
  'Baybay Elementary School',
  'Benigwayan Elementary School',
  'Calatcat Elementary School  ',
  'Lagtang Elementary School',
  'Lanao Elementary School',
  'Loguilo Elementary School',
  'Lourdes Elementary School',
  'Lumbo Elementary School',
  'Molocboloc Elementary School',
  'Sampatulog Elementary School',
  'Sungay Elementary',
  'Talaba Elementary School',
  'Taparak Elementary School',
  'Tugasnon Elementary School',
  'Tula Elementary School',
];

List highSchool1 = [
  'Alubijid National Comprehensive High School',
  'Lourdes National High School',
  'Living Hope Christian Academy (Private)',
];

List college1 = [
  'University of Science and Technology of Southern Philippines (Main Campus)',
  'Bukidnon State University - Alubijid Extension',
];

List barangay1 = [
  'Baybay',
  'Benigwayan',
  'Calatcat',
  'Lagtang  ',
  'Lanao',
  'Loguilo',
  'Lourdes',
  'Lumbo',
  'Molocboloc',
  'Poblacion',
  'Sampatulog',
  'Sungay',
  'Talaba',
  'Taparak',
  'Tugasnon',
  'Tula',
];


List elementary2 = [
  'Alliance Learning Center of Balingasag',
  'Balingasag Baptist Christian School',
  'Balingasag Central School',
  'Bagaay Elementary School',
  'Balagnan Integrated School',
  'Baliwagan Central School',
  'Binitinan Elementary School',
  'Blanco Elementary School',
  'CalaCala Elementary School  ',
  'Calawag Integrated School',
  'Camuayan Elementary School',
  'Cogon Elementary School',
  'Dansuli Elementary School',
  'Gumpot Elementary School',
  'Hermano Elementary School',
  'Holy Child Montessori of Balingasag',
  'Kibalus Elementary School',
  'Kibanban Integrated School',
  'Kinanao Pamalihi Elementary School',
  'Lantad Integrated School',
  'LapuLapu Elementary School',
  'Linabu Integrated School',
  'Mambayaan Integrated School',
  'Mandangoa Elementary School',
  'Misamis Oriental Institute of Science and Technology',
  'Napaliran  Elementary School',
  'Qasah Christian School',
  'Quezon Integrated School',
  'Rosario Elementary School',
  'Samay Integrated School',
  'San Francisco Elementary School',
  'San Isidro Elementary School  ',
  'San Juan Elementary School',
  'St.Peter\'s College of Balingasag, Inc.',
  'St.Rita\'s College of Balingasag',
  'Sulo Elementary School',
  'Talusan Elementary School',
  'Upper Hermano Elementary School',
  'Waterfal Elementary School',
];

List highSchool2 = [
  'Balingasag Senior High School',
  'Baliwagan National High School',
  'Misamis Oriental Institute of Science and Technology',
  'Misamis Oriental National High School',
  'Rosario National High School',
  'San Isidro National High School',
  'San Juan National High School',
  'St.Peter\'s College of Balingasag Inc',
  'St.Rita\'s College of Balingasag',

];

List college2 = [
  'Misamis Oriental Institute of Science and Technology',
  'St.Peter\'s College of Balingasag',
  'St.Rita\'s College of Balingasag',
];

List barangay2 = [
  'Balagnan',
  'Baliwagan',
  'San Francisco',
  'Binitinan  ',
  'Blanco',
  'Calawag',
  'Camuayan',
  'Cogon',
  'Dansuli',
  'Dumarait',
  'Hermano',
  'Kibanban',
  'Linabu',
  'Linggangao',
  'Mambayaan',
  'Mandangoa',
  'Napaliran',
  'Barangay 1 (Poblacion)',
  'Barangay 2 (Poblacion)',
  'Barangay 3 (Poblacion)',
  'Barangay 4 (Poblacion)',
  'Barangay 5 (Poblacion)',
  'Barangay 6 (Poblacion)',
  'Quezon',
  'Rosario',
  'Samay',
  'San Isidro',
  'San Juan',
  'Talusan',
  'Waterfall',
];

List elementary3 = [
  'Balingoan Central School',
  'Bauk-bauk Elementary School',
  'Dahilig Elementary School',
  'Kabangasan Elementary School',
  'Kabulakan Integrated School',
  'Kauswagan Elementary School',
  'Lapinig Elementary School',
  'Mantangale Elementary School  ',
  'Mapua Elementary School',
  'San Alonzo Elementary School',
];

List highSchool3 = [
  'Mantangale National High School',
];

List college3 = [
  ''
];

List barangay3 = [
  'Baukbauk (Poblacion)',
  'Dahilig',
  'Kabangasan',
  'Kabulakan  ',
  'Kauswagan',
  'Lapinig (Poblacion)',
  'Mantangale',
  'Mapua',
  'San Alonzo',
];

List elementary4 = [
  'Binuangan Central School',
  'Dampias Elementary School',
  'Kitamban Elementary School',
  'Kitambis Elementary School',
  'Mabini Elementary School',
  'Mosangot Elementary School',
  'Nabataan Primary School',
  'Valdeconcha Integrated School',
];

List highSchool4 = [
  'Binuangan National High School',
  'Dampias National High School',
];

List college4 = [
  ''
];

List barangay4 = [
  'Dampias',
  'Kitamban',
  'Kitambis',
  'Mabini  ',
  'Mosangot',
  'Nabataan',
  'Poblacion',
  'Valdeconcha',
];

List elementary5 = [
  'Abbas Orchard Montessori School',
  'Angelicum Learning Center',
  'Assumption Montessori School',
  'Baikingon Elementary School',
  'Balubal Elementary School',
  'Balulang Elementary School',
  'Bayabas Elementary School',
  'Bayanga Elementary School',
  'Besigan Elementary School',
  'Blessed Child Academy',
  'Blessed Mother College',
  'Bonbon Elementary School',
  'Bongbongon Elementary School',
  'Bugo Central School',
  'Bugo Christian School',
  'Cagayan de Oro Adventist Elementary School',
  'Cagayan de Oro Christian School',
  'Cagayan de Oro College',
  'Calaanan Elementary School',
  'Camaman-an Elementary School',
  'Camp Evangelista Elementary School',
  'Canitoan Elementary School',
  'Capitol University Basic Education Department',
  'Children\'s Progressive School',
  'City Central School',
  'Consolacion Elementary School',
  'Corpus Christi School',
  'Corrales Elementary School',
  'Cugman Elementary School ',
  'Dansolihon Elementary School',
  'Diamond Evangelical School',
  'Divine Mercy School',
  'East City Central School',
  'First Baptist Academy',
  'Fr. William F. Masterson, S.J. Elementary School',
  'F.S. Catanico Elementary School',
  'Golden Boulevard Seventh-day Adventist Elementary School',
  'Grent Learning Center',
  'Gusa Elementary School',
  'Holy Trinity Learning Center',
  'Immanuel Mission International School',
  'Indahag Elementary School',
  'International School',
  'Iponan Elementary School',
  'Kamakawan Elementary School',
  'Kauswagan Central School',
  'Kiam-is Elementary School',
  'Kong Hua School',
  'Liceo de Cagayan University',
  'Linangohan Elementary School',
  'Lourdes College Grade School',
  'Lumbia Elementary School',
  'Macabalan Elementary School',
  'Macanhan Elementary School',
  'Macasandig Elementary School',
  'Magayad Elementary School',
  'Malasag Elementary School',
  'Mambuaya Elementary School',
  'Mary-Infant Jesus School',
  'Marymount Academy',
  'Merry Child School',
  'Montessori De Oro',
  'Nanuri International School',
  'North City Central School',
  'Oro Christian Grace School',
  'Oro Institute of Technology',
  'Pagalungan Elementary School',
  'Pagatpat Elementary School',
  'Palalan Elementary School',
  'Philippine Southfield School',
  'Philadelphian Christian Academy',
  'Pigsag-an Elementary School',
  'Pilgrim Christian College',
  'Puerto Elementary School',
  'Rosevale School',
  'Sacred Heart Academy',
  'Sacred Heart of Jesus Montessori School',
  'Sacred Heart Village Elementary School',
  'San Simon Elementary School',
  'Shekinah Glory Christian Academy',
  'South City Central School',
  'Southern Philippines College',
  'St. Francis Learning Center',
  'St. Joseph School',
  'St. Mary\'s Academy of Carmen',
  'St. Mary\'s School',
  'Sta. Cecilia Learning Center',
  'Suntingon Elementary School',
  'Tablon Elementary School',
  'Taglimao Elementary School',
  'Taguanao Elementary School',
  'Tagpangi Elementary School',
  'Tignapoloan Elementary School',
  'Tuburan Elementary School',
  'Tumpagon Elementary School',
  'Upper Carmen Elementary School',
  'Vita Basic Education School',
  'West City Central School',
  'Xavier University Grade School',
];

List highSchool5 = [
  'Abbas Orchard Montessori School',
  'Agusan National High School',
  'Angeles Sisters National High School',
  'Angelicum Learning Center',
  'Assumption Montessori School',
  'Balulang National High School',
  'Balubal National High School',
  'Bayabas National High School',
  'Bayanga National High School',
  'Besigan National High School',
  'Blessed Child Academy',
  'Blessed Mother College',
  'Bonbon National High School',
  'Bugo National High School',
  'Bulua National High School',
  'Cagayan de Oro College',
  'Cagayan de Oro National High School',
  'Camaman-an National High School',
  'Canitoan National High School',
  'Capitol University Basic Education Department',
  'Carmen National High School',
  'Consolacion National High School',
  'Corpus Christi School',
  'Cugman National High School',
  'Dansolihon National High School',
  'Divine Mercy School',
  'East Gusa National High School',
  'F.S. Catanico National High School',
  'Gusa Regional Science High School - X',
  'Immanuel Mission International School',
  'Indahag National High School',
  'International School',
  'Kauswagan National High School',
  'Kong Hua School',
  'Lapasan National High School',
  'Liceo de Cagayan University',
  'Lourdes College',
  'Lumbia National High School',
  'Macabalan National High School',
  'Macasandig National High School',
  'Mambuaya National High School',
  'Marymount Academy',
  'Merry Child School',
  'Misamis Oriental General Comprehensive High School',
  'Montessori De Oro',
  'Nanuri International School',
  'Oro Christian Grace School',
  'Patag National High School (BULUA NHS ANNEX)',
  'Pagatpat National High School',
  'Pedro "Oloy" N. Roa Sr. High School',
  'Philippine Southfield School',
  'Philadelphian Christian Academy',
  'Pigsag-an National High School',
  'Pilgrim Christian College',
  'Puerto National High School',
  'Puntod National High School',
  'Sacred Heart Academy',
  'Sacred Heart of Jesus Montessori School',
  'San Simon National High School',
  'Shekinah Glory Christian Academy',
  'Southern Philippines College',
  'St. Mary\'s Academy of Carmen',
  'St. Mary\'s School',
  'Sta. Cecilia Learning Center',
  'Tablon National High School',
  'Taglimao National High School',
  'Tignapoloan National High School',
  'Tuburan National High School',
  'Tumpagon National High School',
  'Vita Basic Education School',
  'Xavier University High School',
];

List college5 = [
  'AMA COMPUTER COLLEGE - CAGAYAN DE ORO CITY INC.',
  'Blessed Mother College',
  'Bukidnon State University - MOGCHS ESC',
  'Cagayan de Oro College',
  'Capitol University',
  'GOLDEN HERITAGE POLYTECHNIC COLLEGE',
  'Informatics Institute',
  'Liceo de Cagayan University',
  'Lourdes College',
  'Oro Bible College',
  'Pilgrim Christian College',
  'Southern Philippines College',
  'STI College',
  'St. Mary\'s Academy of Carmen',
  'University of Science and Technology of Southern Philippines (USTSP)',
  'VINEYARD INTERNATIONAL POLYTECHNIC COLLEGE, INC.',
  '\nXavier University – Ateneo de Cagayan',
];

List barangay5 = [
  'Agusan',
  'Baikingon',
  'Balubal',
  'Balulang',
  'Barangay 1',
  'Barangay 2',
  'Barangay 3',
  'Barangay 4',
  'Barangay 5',
  'Barangay 6',
  'Barangay 7',
  'Barangay 8',
  'Barangay 9',
  'Barangay 10',
  'Barangay 11',
  'Barangay 12',
  'Barangay 13',
  'Barangay 14',
  'Barangay 15',
  'Barangay 16',
  'Barangay 17',
  'Barangay 18',
  'Barangay 19',
  'Barangay 20',
  'Barangay 21',
  'Barangay 22',
  'Barangay 23',
  'Barangay 24',
  'Barangay 25',
  'Barangay 26',
  'Barangay 27',
  'Barangay 28',
  'Barangay 29',
  'Barangay 30',
  'Barangay 31',
  'Barangay 32',
  'Barangay 33',
  'Barangay 34',
  'Barangay 35',
  'Barangay 36',
  'Barangay 37',
  'Barangay 38',
  'Barangay 39',
  'Barangay 40',
  'Bayabas',
  'Bayanga',
  'Besigan',
  'Bonbon',
  'Bugo',
  'Bulua',
  'Camaman-an',
  'Canitoan',
  'Carmen',
  'Consolacion',
  'Cugman'
  'Dansolihon',
  'F.S. Catanico',
  'Gusa',
  'Indahag',
  'Iponan',
  'Kauswagan',
  'Lapasan',
  'Lumbia',
  'Macabalan',
  'Macasandig',
  'Mambuaya',
  'Nazareth',
  'Pagalungan',
  'Pagatpat',
  'Patag',
  'Pigsag-an',
  'Puerto',
  'Puntod',
  'San Simon',
  'Tablon',
  'Taglimao',
  'Tagpangi',
  'Tignapoloan',
  'Tuburan',
  'Tumpagon',
];
List elementary6 = [
  'Claveria Central School',
  'Cherubims Learning Center Inc.',
  'Doalnara Agricultural Academy',
  'Mat-i Central School',
  'Our Lady of Lourdes Academy of Claveria',
];

List highSchool6 = [
  'Doalnara Agricultural Academy',
  'Our Lady of Lourdes Academy of Claveria',
  'Mat-i National High School',
  'Aposkahoy National High School',
  'Rizal National High School',
  'Hinaplanan National High School',
  'Malagana National High School',
  'Patrocinio National High School',
  'Dr. Gerardo Sabal Memorial National High School',


];

List college6 = [
  'University of Science and Technology of Southern Philippines (USTsP) - Claveria Campus',
];

List barangay6 = [
  'Ani-e',
  'Aposkahoy',
  'Bulahan',
  'Cabacungan',
  'Pelaez',
  'Gumaod',
  'Hinaplanan',
  'Kalawitan',
  'Lanise',
  'Luna',
  'Madaguing',
  'Malagana',
  'Minalwang',
  'Mat-I',
  'Panampawan',
  'Parmbugas',
  'Patrocinio',
  'Plaridel',
  'Poblacion',
  'Punong',
  'Rizal',
  'Santa Cruz',
  'Tamboboan',
  'Tipolohon',
];

List elementary7 = [
  'Amoros Elementary School',
  'Bolisong Elementary School',
  'Cogon Elementary School',
  'El Salvador City Central School',
  'Himaya Elementary School',
  'Hinigdaan Elementary School',
  'Kalabay-labay Elementary School',
  'Molugan Elementary School',
  'Quibonbon Elementary School',
  'Sambulawan Elementary School',
  'San Francisco de Asis Elementary School',
  'Sinaloc Elementary School',
  'Stellulae Mariae School',
  'Taytay Elementary School',
  'Ulaliman Elementary School',

];

List highSchool7 = [
  'Cogon National High School',
  'Hinigdaan National High School',
  'Molugan National High School',
  'St. Joseph Academy of El Salvador'
];

List college7 = [
  'THE NEW EL SALVADOR COLLEGES, INC.',
];

List barangay7 = [
  'Amoros',
  'Bolisong',
  'Cogon',
  'Himaya',
  'Hinigdaan',
  'Kalabaylabay',
  'Molugan',
  'Pedro S. Baculio (Bolo-Bolo)',
  'Poblacion',
  'Quibonbon',
  'Sambulawan',
  'San Francisco de Asis (Calongonan)',
  'Sinaloc',
  'Taytay',
  'Ulaliman',
];

List elementary8 = [
  'Amoros Elementary School',
  'Bolisong Elementary School',
  'Cogon Elementary School',
  'El Salvador City Central School',
  'Himaya Elementary School',
  'Hinigdaan Elementary School',
  'Kalabay-labay Elementary School',
  'Molugan Elementary School',
  'Quibonbon Elementary School',
  'Sambulawan Elementary School',
  'San Francisco de Asis Elementary School',
  'Sinaloc Elementary School',
  'Stellulae Mariae School',
  'Taytay Elementary School',
  'Ulaliman Elementary School',

];

List highSchool8 = [
  'Cogon National High School',
  'Hinigdaan National High School',
  'Molugan National High School',
  'St. Joseph Academy of El Salvador'
];

List college8 = [
  'Christ the King College',
  'Gingoog Christian College',
  'Gingoog City Junior College',
  'Guevarra Institute of Technology',
];

List barangay8 = [
  'Agay-ayan',
  'Alagatan',
  'Anakan',
  'Bagubad',
  'Bakidbakid',
  'Bal-ason',
  'Bantaawan',
  'Barangay 1',
  'Barangay 2',
  'Barangay 3',
  'Barangay 4',
  'Barangay 5',
  'Barangay 6',
  'Barangay 7',
  'Barangay 8',
  'Barangay 9',
  'Barangay 10',
  'Barangay 11',
  'Barangay 12',
  'Barangay 13',
  'Barangay 14',
  'Barangay 15',
  'Barangay 16',
  'Barangay 17',
  'Barangay 18',
  'Barangay 18-A',
  'Barangay 19',
  'Barangay 20',
  'Barangay 21',
  'Barangay 22',
  'Barangay 22-A',
  'Barangay 23',
  'Barangay 24',
  'Barangay 24-A',
  'Barangay 25',
  'Barangay 26',
  'Binakalan',
  'Capitulangan',
  'Daan-Lungsod',
  'Dinawehan',
  'Eureka',
  'Hindangon',
  'Kalagonoy',
  'Kalipay',
  'Kamanikan',
  'Kianlagan',
  'Kibuging',
  'Kipuntos',
  'Lawaan',
  'Lawit',
  'Libertad',
  'Libon',
  'Lunao',
  'Lunotan',
  'Malibud',
  'Malinao',
  'Maribucao',
  'Mimbuntong',
  'Mimbalagon',
  'Mimbunga',
  'Minsapinit',
  'Murallon',
  'Odiongan',
  'Pangasihan',
  'Pigsaluhan',
  'Punong',
  'Ricoro',
  'Samay',
  'Sangalan',
  'San Jose',
  'San Juan',
  'San Luis',
  'San Miguel',
  'Santiago',
  'Tagpako',
  'Talisay',
  'Talon',
  'Tinabalan',
  'Tinulongan',
];



final List<Info> infos = [
  Info(
    municipality: 'Alubijid',
    imageUrl: 'assets/Alubijid_Misamis_Oriental.png',
    description:
        'The municipality name, "Alubijid", pronounced alubihid due to Spanish accent, is the local term for the hog plum tree, Alubijid, along with El Salvador, was part of Cagayan de Misamis (present-day Cagayan de Oro) when the two entities petitioned to become municipalities in 1933. Alubijid became a separate town in 1940, and El Salvador became one 9 years later.',
    barangay: barangay1,
    elementary: elementary1,
    highSchool: highSchool1,
    college: college1,
  ),
  Info(
    municipality: 'Balingasag',
    imageUrl: 'assets/balingasag-logo-removebg-preview.png',
    description:
        '''Balingasag started as a pre-Hispanic settlement, which was eventually discovered by the Spaniards when they came to colonize the Philippines. Presumably, the name came from two contracted Cebuano words "baling", which means fishing net, and "kasag", crab. Legend has it that one day during the Spanish regime a group of guardia civil, while patrolling the seashore near the settlement of the natives, chanced upon some fishermen pulling fishing nets. A guardian civil asked a fisherman for the name of the place. Not understanding the language and thinking that he was asked what he what was doing, the fisherman, pointing his finger to the net, answered “baling”, and then turning it to the contents of the boat nearby, added “kasag”.''',
    barangay: barangay2,
    elementary: elementary2,
    highSchool: highSchool2,
    college: college2,
  ),
  Info(
    municipality: 'Balingoan',
    imageUrl: 'assets/Balingoan_logo.png',
    description:
    '''Formerly part of Talisayan, it gained independence on March 1, 1952. According to the local legend, it derived its name from the word "baling ni juan" (John's Fishing Net), which later on became simply as "Balingoan".''',
    barangay: barangay3,
    elementary: elementary3,
    highSchool: highSchool3,
    college: college3,
  ),
  Info(
    municipality: 'Binuangan',
    imageUrl: 'assets/binuangan_logo-removebg-preview.png',
    description:
    '''Binuangan, officially the Municipality of Binuangan (Cebuano: Lungsod sa Binuangan; Tagalog: Bayan ng Binuangan), is a 6th class municipality in the province of Misamis Oriental, Philippines. According to the 2015 census, it has a population of 7,515 people''',
    barangay: barangay4,
    elementary: elementary4,
    highSchool: highSchool4,
    college: college4,
  ),
  Info(
    municipality: 'Cagayan de Oro',
    imageUrl: 'assets/Cagayan_de_Oro_official_seal,_2014.png',
    description:
    '''The name Cagayan de Oro (lit. River of Gold)can be traced back to the arrival of the Spanish Augustinian Recollect friars in 1622, the area around Himologan (now Huluga), was already known as "Cagayán". Early Spanish written documents in the 16th century already referred to the place as "Cagayán". The region of Northern Mindanao, which included Cagayan de Oro, was granted as encomienda to a certain Don Juan Griego on January 25, 1571. It was then former Vice President of the Philippines Emmanuel Peláez who appended de Oro to Cagayan. There are also other places in the Philippines with the Cagayan name; these include the province of Cagayan in northern Luzon, the Cagayan Islands in the northern Sulu Sea, and the island of Mapun in Tawi-Tawi (formerly known as Cagayan de Sulu).''',
    barangay: barangay5,
    elementary: elementary5,
    highSchool: highSchool5,
    college: college5,
  ),
  Info(
    municipality: 'Claveria',
    imageUrl: 'assets/CLAVERIA_SEAL-removebg-preview.png',
    description:
    '''The town was once named Tikala, a native term for “wonder”. Tikala was once ruled by Datu Manlumupog, a warrior of the native aborigines known as the “Higaunons”, meaning people of the land. The Higaunons observed simple living but with high regard to nature. For them, the vast and rich environment they have means life to them and this is manifested by their unique datu system, e.g., Datu for Agriculture – Igbabasuk; Datu for Hunting – Panumanud; Datu for water respect – Bulalakaw, etc. Despite the simple way of life, they were kept united by their Sacred Code named as Bungkatel Ha Bulawan, which under its teaching, land is a gift from the supreme creator for all men, the Magbabaya. Land is life, thus, must be taken cared of under the stewardship of the great, great-great ancestors whose spirits continue to keep watching over it so it could be used for generation to generation.''',
    barangay: barangay6,
    elementary: elementary6,
    highSchool: highSchool6,
    college: college6,
  ),
  Info(
    municipality: 'El Salvador',
    imageUrl: 'assets/Seal_of_El_Salvador,_Misamis_Oriental.png',
    description:
    '''El Salvador was created from the barrios of El Salvador and Molugan with their sitios known as Sala, Sambulawan, Sinaloc, Lagtang, Talaba, Kalabaylabay and Hinigdaan, formerly part of Cagayan de Misamis, Misamis Oriental, in 1948. Hinigdaan was a ranch during the Spanish periods the areas covers the parts of Kalabay labay where the DJango's have 300 hectares of land and hundreds of cows..the area was famous of cattle ranching towards the areas of Tugasnon alubijid to Lourdes where the first Municipality was located now transferred to Alubijid and Sikitun of Gitagum Misamis Oriental.''',
    barangay: barangay7,
    elementary: elementary7,
    highSchool: highSchool7,
    college: college7,
  ),
  Info(
    municipality: 'Gingoog',
    imageUrl: 'assets/Gingoog_Misamis_Oriental.png',
    description:
    '''The term Gingoog originally came from the word "Hingoog", which means "Goodluck", from a Lumad tribe of Manobo who settled in the area. The word implies good fortune, thus Gingoog City means the City of Good Luck. The natives of this place are the ones with the family names of "Gingco", and "Gingoyon". Gingoog was founded as a mission by Spanish missionaries in 1750. It was one of the oldest localities in Misamis Oriental Province, older than the province's capital and economic hub, Cagayan de Oro which was founded in 1871. It was made part of the town of Talisayan until it was incorporated as an independent municipality in 1908. In 1957, the sitio of Binuangan was converted into a barrio known as Talisay. Gingoog was turned into a city via Republic Act No. 2668 signed by President Carlos P. Garcia circa June 18, 1960.''',
    barangay: barangay8,
    elementary: elementary8,
    highSchool: highSchool8,
    college: college8,
  ),


];
